language: d

os:
  - linux
  - osx

env:
  - ARCH=x86 CONFIG=x11
  - ARCH=x86 CONFIG=default
  - ARCH=x86_64 CONFIG=x11
  - ARCH=x86_64 CONFIG=default
  
matrix:
  exclude:
    - os: osx
      env: ARCH=x86 CONFIG=x11
    - os: osx
      env: ARCH=x86 CONFIG=default
    - os: osx
      env: ARCH=x86_64 CONFIG=x11

sudo: true
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$ARCH" == "x86" ]]; then sudo apt-get install gcc-multilib; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CONFIG" == "x11" ]]; then sudo apt-get install libx11-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CONFIG" == "x11" && "$ARCH" == "x86" ]]; then sudo apt-get install libx11-dev:i386; fi
script:
  - dub build --compiler=${DC} --arch=${ARCH} --config=${CONFIG}
  - file travis-test
  - ls -lh travis-test
